// Code Generated by Sidekick is for learning and experimentation purposes only.
import { HttpResponse } from 'msw';

/**
 * Check if a token is expired
 */
export const isTokenExpired = (token: string): boolean => {
    // Check if it's the special "EXPIRED" token (for testing)
    if (token.includes('EXPIRED_TOKEN')) {
        console.log('MSW: Token is marked as EXPIRED');
        return true;
    }
    
    // For real tokens, check timestamp
    const parts = token.split('-');
    const timestamp = parseInt(parts[parts.length - 1]);
    
    if (!timestamp || isNaN(timestamp)) {
        console.log('MSW: No timestamp in token');
        return false;
    }
    
    const isAccessToken = token.startsWith('access-token');
    const expirationTime = isAccessToken 
        ? 15 * 60 * 1000       // Access: 15 minutes
        : 7 * 24 * 60 * 60 * 1000; // Refresh: 7 days
    const tokenAge = Date.now() - timestamp;
    const isExpired = tokenAge > expirationTime;
    
    console.log(`MSW: Token age: ${Math.floor(tokenAge / 1000)}s, Expired: ${isExpired}`);
    
    return isExpired;
};

/**
 * Validate auth token from request
 * Returns either success with userId or error response
 */
export const validateAuthToken = (request: Request): 
    { success: true; userId: string } | 
    { success: false; response: Response } =>
{
    const authHeader = request.headers.get('Authorization');
        
    // Check if header exists and has correct format
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
        console.log('MSW: No valid auth header');
        return {
            success: false,
            response: HttpResponse.json(
                { message: 'Unauthorized' },
                { status: 401 }
            )
        };
    }
    
    // Extract token
    const token = authHeader.replace('Bearer ', '');
    
    // Check if expired
    if (isTokenExpired(token)) {
        console.log('MSW: Token EXPIRED, returning 401');
        return {
            success: false,
            response: HttpResponse.json(
                { message: 'Token expired' },
                { status: 401 }
            )
        };
    }
    
    // Extract user ID from token
    const userId = token.split('-')[2];
    
    console.log('MSW: Valid token for user:', userId);
    
    return { success: true, userId };
};
